In [4]:
import pandas as pd

In [55]:
df=pd.read_csv("customer_data.csv")

In [6]:
df.head()

,id,age,gender,income,education,region,loyalty_status,purchase_frequency,purchase_amount,product_category,promotion_usage,satisfaction_score
0,1,27,Male,40682,Bachelor,East,Gold,frequent,18249,Books,0,6
1,2,29,Male,15317,Masters,West,Regular,rare,4557,Clothing,1,6
2,3,37,Male,38849,Bachelor,West,Silver,rare,11822,Clothing,0,6
3,4,30,Male,11568,HighSchool,South,Regular,frequent,4098,Food,0,7
4,5,31,Female,46952,College,North,Regular,occasional,19685,Clothing,1,5

In [7]:
df.tail()

,id,age,gender,income,education,region,loyalty_status,purchase_frequency,purchase_amount,product_category,promotion_usage,satisfaction_score
99995,99996,31,Female,19691,College,West,Regular,occasional,7075,Health,0,7
99996,99997,36,Male,17428,HighSchool,South,Regular,rare,6873,Health,0,5
99997,99998,29,Male,13222,College,West,Regular,frequent,5152,Clothing,0,5
99998,99999,31,Female,40093,Bachelor,West,Regular,frequent,16312,Health,1,5
99999,100000,35,Female,22249,College,West,Silver,rare,9426,Health,0,6

In [8]:
df.info()
#getting non null data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  100000 non-null  int64
 1   age                 100000 non-null  int64
 2   gender              100000 non-null  object
 3   income              100000 non-null  int64
 4   education           100000 non-null  object
 5   region              100000 non-null  object
 6   loyalty_status      100000 non-null  object
 7   purchase_frequency  100000 non-null  object
 8   purchase_amount     100000 non-null  int64
 9   product_category    100000 non-null  object
 10  promotion_usage     100000 non-null  int64
 11  satisfaction_score  100000 non-null  int64
dtypes: int64(6), object(6)
memory usage: 9.2+ MB

In [9]:
df.describe()

,id,age,income,purchase_amount,promotion_usage,satisfaction_score
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,30.003260,27516.269880,9634.790840,0.300800,5.009650
std,28867.657797,4.480535,12996.782587,4799.339449,0.458608,1.038714
min,1.000000,12.000000,5000.000000,1118.000000,0.000000,0.000000
25%,25000.750000,27.000000,16271.750000,5583.000000,0.000000,4.000000
50%,50000.500000,30.000000,27584.500000,9452.000000,0.000000,5.000000
75%,75000.250000,33.000000,38747.250000,13350.000000,1.000000,6.000000
max,100000.000000,49.000000,50000.000000,26204.000000,1.000000,10.000000

In [10]:
df.columns

Index(['id', 'age', 'gender', 'income', 'education', 'region',
       'loyalty_status', 'purchase_frequency', 'purchase_amount',
       'product_category', 'promotion_usage', 'satisfaction_score'],
      dtype='object')

In [11]:
df["age"]

0        27
1        29
2        37
3        30
4        31
         ..
99995    31
99996    36
99997    29
99998    31
99999    35
Name: age, Length: 100000, dtype: int64

In [12]:
df[["age","income","education"]] #give the columns

       age  income   education
0       27   40682    Bachelor
1       29   15317     Masters
2       37   38849    Bachelor
3       30   11568  HighSchool
4       31   46952     College
...    ...     ...         ...
99995   31   19691     College
99996   36   17428  HighSchool
99997   29   13222     College
99998   31   40093    Bachelor
99999   35   22249     College

[100000 rows x 3 columns]

In [13]:
df.loc[df["age"]>30]

,id,age,gender,income,education,region,loyalty_status,purchase_frequency,purchase_amount,product_category,promotion_usage,satisfaction_score
2,3,37,Male,38849,Bachelor,West,Silver,rare,11822,Clothing,0,6
4,5,31,Female,46952,College,North,Regular,occasional,19685,Clothing,1,5
5,6,38,Male,7347,Bachelor,South,Silver,occasional,2822,Electronics,0,5
6,7,32,Female,8265,Bachelor,South,Silver,frequent,3293,Clothing,0,7
10,11,35,Male,43896,HighSchool,South,Regular,rare,16158,Home,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...
99993,99994,37,Female,37380,College,South,Regular,rare,13238,Food,0,5
99995,99996,31,Female,19691,College,West,Regular,occasional,7075,Health,0,7
99996,99997,36,Male,17428,HighSchool,South,Regular,rare,6873,Health,0,5
99998,99999,31,Female,40093,Bachelor,West,Regular,frequent,16312,Health,1,5
99999,100000,35,Female,22249,College,West,Silver,rare,9426,Health,0,6

In [14]:
df.iloc[0:5,0:3] #index based

   id  age  gender
0   1   27    Male
1   2   29    Male
2   3   37    Male
3   4   30    Male
4   5   31  Female

In [16]:
df.isnull().sum()#to find the null values

id                    0
age                   0
gender                0
income                0
education             0
region                0
loyalty_status        0
purchase_frequency    0
purchase_amount       0
product_category      0
promotion_usage       0
satisfaction_score    0
dtype: int64

In [19]:
df.dropna(subset=["age"]) #it is used when we find that age has null values ,then we are drop the empty rows

,id,age,gender,income,education,region,loyalty_status,purchase_frequency,purchase_amount,product_category,promotion_usage,satisfaction_score
0,1,27,Male,40682,Bachelor,East,Gold,frequent,18249,Books,0,6
1,2,29,Male,15317,Masters,West,Regular,rare,4557,Clothing,1,6
2,3,37,Male,38849,Bachelor,West,Silver,rare,11822,Clothing,0,6
3,4,30,Male,11568,HighSchool,South,Regular,frequent,4098,Food,0,7
4,5,31,Female,46952,College,North,Regular,occasional,19685,Clothing,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,31,Female,19691,College,West,Regular,occasional,7075,Health,0,7
99996,99997,36,Male,17428,HighSchool,South,Regular,rare,6873,Health,0,5
99997,99998,29,Male,13222,College,West,Regular,frequent,5152,Clothing,0,5
99998,99999,31,Female,40093,Bachelor,West,Regular,frequent,16312,Health,1,5
99999,100000,35,Female,22249,College,West,Silver,rare,9426,Health,0,6

In [24]:
df1=df.head(3)
df2=df.tail(3)
pd.concat([df1,df2]) #concating the values

,id,age,gender,income,education,region,loyalty_status,purchase_frequency,purchase_amount,product_category,promotion_usage,satisfaction_score
0,1,27,Male,40682,Bachelor,East,Gold,frequent,18249,Books,0,6
1,2,29,Male,15317,Masters,West,Regular,rare,4557,Clothing,1,6
2,3,37,Male,38849,Bachelor,West,Silver,rare,11822,Clothing,0,6
99997,99998,29,Male,13222,College,West,Regular,frequent,5152,Clothing,0,5
99998,99999,31,Female,40093,Bachelor,West,Regular,frequent,16312,Health,1,5
99999,100000,35,Female,22249,College,West,Silver,rare,9426,Health,0,6

In [25]:
df3=pd.read_csv("netflix_titles.csv")

In [28]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [29]:
df3.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [52]:
df3.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [53]:
df3.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [35]:
#df3.dropna(subset=["director","cast","country","duration","date_added","rating"],inplace=True)

In [54]:
df3.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [38]:
df3.describe()

       release_year
count   5332.000000
mean    2012.742123
std        9.625831
min     1942.000000
25%     2011.000000
50%     2016.000000
75%     2018.000000
max     2021.000000

In [39]:
df.columns

Index(['id', 'age', 'gender', 'income', 'education', 'region',
       'loyalty_status', 'purchase_frequency', 'purchase_amount',
       'product_category', 'promotion_usage', 'satisfaction_score'],
      dtype='object')

In [40]:
df3.index

Index([   7,    8,    9,   12,   24,   27,   28,   29,   38,   41,
       ...
       8792, 8793, 8794, 8798, 8799, 8801, 8802, 8804, 8805, 8806],
      dtype='int64', length=5332)

In [48]:
df3.loc[df3["type"] == "Movie"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [51]:
df3.loc[df3["release_year"]==2009]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
58,s59,Movie,Naruto Shippûden the Movie: The Will of Fire,Masahiko Murata,"Junko Takeuchi, Chie Nakamura, Kazuhiko Inoue,...",Japan,"September 15, 2021",2009,TV-PG,96 min,"Action & Adventure, Anime Features, Internatio...",When four out of five ninja villages are destr...
115,s116,Movie,Bright Star,Jane Campion,"Abbie Cornish, Ben Whishaw, Paul Schneider, Ke...","United Kingdom, Australia, France","September 2, 2021",2009,PG,119 min,"Dramas, Romantic Movies",This drama details the passionate three-year r...
330,s331,Movie,Cloudy with a Chance of Meatballs,"Phil Lord, Christopher Miller","Bill Hader, Anna Faris, James Caan, Andy Sambe...","United States, Canada","August 1, 2021",2009,PG,90 min,"Children & Family Movies, Comedies, Sci-Fi & F...",When inventor Flint Lockwood makes clouds rain...
347,s348,Movie,Planet 51,Jorge Blanco,"Justin Long, Dwayne Johnson, Gary Oldman, Sean...","Spain, United Kingdom, United States","August 1, 2021",2009,PG,91 min,"Children & Family Movies, Comedies, Sci-Fi & F...",After landing on a planet reminiscent of 1950s...
415,s416,Movie,Chhota Bheem aur Krishna,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"July 22, 2021",2009,TV-Y7,68 min,Children & Family Movies,"Centuries after the end of a conqueror's rule,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8542,s8543,Movie,The Ugly Truth,Robert Luketic,"Katherine Heigl, Gerard Butler, Eric Winter, J...",United States,"April 25, 2019",2009,R,96 min,"Comedies, Romantic Movies",A chauvinistic morning-show commentator tries ...
8664,s8665,Movie,Up in the Air,Jason Reitman,"George Clooney, Vera Farmiga, Anna Kendrick, J...",United States,"January 1, 2020",2009,R,110 min,"Comedies, Dramas, Romantic Movies",Ryan Bingham flies around the country firing e...
8789,s8790,Movie,You Changed My Life,Cathy Garcia-Molina,"John Lloyd Cruz, Sarah Geronimo, Rayver Cruz, ...",Philippines,"February 27, 2019",2009,TV-PG,116 min,"Comedies, Dramas, International Movies",Laida and Miggy think they've found perfect ha...
8799,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,"February 15, 2018",2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...

In [61]:
df4=pd.read_csv("netflix2_titles.csv")

In [62]:
df4.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [65]:
df4["director"].fillna("unknown",inplace=True)

In [66]:
df4

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,unknown,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,unknown,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [72]:
pd.pivot_table(df3,index="country",columns="type",aggfunc="count")

                                                    cast         date_added  \
type                                               Movie TV Show      Movie
country
, France, Algeria                                    1.0     NaN        1.0
Argentina                                           34.0     1.0       34.0
Argentina, Brazil, France, Poland, Germany, Den...   1.0     NaN        1.0
Argentina, Chile                                     2.0     NaN        2.0
Argentina, Chile, Peru                               1.0     NaN        1.0
...                                                  ...     ...        ...
Uruguay, Guatemala                                   1.0     NaN        1.0
Uruguay, Spain, Mexico                               1.0     NaN        1.0
Venezuela                                            1.0     NaN        1.0
Vietnam                                              7.0     NaN        7.0
Zimbabwe                                             1.0     NaN        1.0

                                                           description  \
type                                               TV Show       Movie
country
, France, Algeria                                      NaN         1.0
Argentina                                              1.0        34.0
Argentina, Brazil, France, Poland, Germany, Den...     NaN         1.0
Argentina, Chile                                       NaN         2.0
Argentina, Chile, Peru                                 NaN         1.0
...                                                    ...         ...
Uruguay, Guatemala                                     NaN         1.0
Uruguay, Spain, Mexico                                 NaN         1.0
Venezuela                                              NaN         1.0
Vietnam                                                NaN         7.0
Zimbabwe                                               NaN         1.0

                                                           director          \
type                                               TV Show    Movie TV Show
country
, France, Algeria                                      NaN      1.0     NaN
Argentina                                              1.0     34.0     1.0
Argentina, Brazil, France, Poland, Germany, Den...     NaN      1.0     NaN
Argentina, Chile                                       NaN      2.0     NaN
Argentina, Chile, Peru                                 NaN      1.0     NaN
...                                                    ...      ...     ...
Uruguay, Guatemala                                     NaN      1.0     NaN
Uruguay, Spain, Mexico                                 NaN      1.0     NaN
Venezuela                                              NaN      1.0     NaN
Vietnam                                                NaN      7.0     NaN
Zimbabwe                                               NaN      1.0     NaN

                                                   duration         listed_in  \
type                                                  Movie TV Show     Movie
country
, France, Algeria                                       1.0     NaN       1.0
Argentina                                              34.0     1.0      34.0
Argentina, Brazil, France, Poland, Germany, Den...      1.0     NaN       1.0
Argentina, Chile                                        2.0     NaN       2.0
Argentina, Chile, Peru                                  1.0     NaN       1.0
...                                                     ...     ...       ...
Uruguay, Guatemala                                      1.0     NaN       1.0
Uruguay, Spain, Mexico                                  1.0     NaN       1.0
Venezuela                                               1.0     NaN       1.0
Vietnam                                                 7.0     NaN       7.0
Zimbabwe                                                1.0     NaN       1.0

                                                           rating          \
type                                               TV Show  Movie TV Show
country
, France, Algeria                                      NaN    1.0     NaN
Argentina                                              1.0   34.0     1.0
Argentina, Brazil, France, Poland, Germany, Den...     NaN    1.0     NaN
Argentina, Chile                                       NaN    2.0     NaN
Argentina, Chile, Peru                                 NaN    1.0     NaN
...                                                    ...    ...     ...
Uruguay, Guatemala                                     NaN    1.0     NaN
Uruguay, Spain, Mexico                                 NaN    1.0     NaN
Venezuela                                              NaN    1.0     NaN
Vietnam                                                NaN    7.0     NaN
Zimbabwe                                               NaN    1.0     NaN

                                                   release_year          \
type                                                      Movie TV Show
country
, France, Algeria                                           1.0     NaN
Argentina                                                  34.0     1.0
Argentina, Brazil, France, Poland, Germany, Den...          1.0     NaN
Argentina, Chile                                            2.0     NaN
Argentina, Chile, Peru                                      1.0     NaN
...                                                         ...     ...
Uruguay, Guatemala                                          1.0     NaN
Uruguay, Spain, Mexico                                      1.0     NaN
Venezuela                                                   1.0     NaN
Vietnam                                                     7.0     NaN
Zimbabwe                                                    1.0     NaN

                                                   show_id         title  \
type                                                 Movie TV Show Movie
country
, France, Algeria                                      1.0     NaN   1.0
Argentina                                             34.0     1.0  34.0
Argentina, Brazil, France, Poland, Germany, Den...     1.0     NaN   1.0
Argentina, Chile                                       2.0     NaN   2.0
Argentina, Chile, Peru                                 1.0     NaN   1.0
...                                                    ...     ...   ...
Uruguay, Guatemala                                     1.0     NaN   1.0
Uruguay, Spain, Mexico                                 1.0     NaN   1.0
Venezuela                                              1.0     NaN   1.0
Vietnam                                                7.0     NaN   7.0
Zimbabwe                                               1.0     NaN   1.0


type                                               TV Show
country
, France, Algeria                                      NaN
Argentina                                              1.0
Argentina, Brazil, France, Poland, Germany, Den...     NaN
Argentina, Chile                                       NaN
Argentina, Chile, Peru                                 NaN
...                                                    ...
Uruguay, Guatemala                                     NaN
Uruguay, Spain, Mexico                                 NaN
Venezuela                                              NaN
Vietnam                                                NaN
Zimbabwe                                               NaN

[604 rows x 20 columns]

In [80]:
df3["country"].isnull().sum()

np.int64(0)

np.int64(0)